version: "3"
services:
  db-leader:
    image: postgres:14
    container_name: ha-db-leader
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=social_net
      - PGPASSFILE=/root/.pgpass
      - PGDATA=${PGDATA_LOCAL}
    volumes:
      - "./db-data-leader/pg_setup.sh:/etc/pg_setup.sh"
      - "./db-data-leader/people.csv:/people.csv"
      - "./db-data-leader/posts.csv:/posts.csv"
      - "./db-data-leader/pgslave:/pgslave"
      - "./db-data-leader/pgpass:/root/.pgpass"
      - "./db/schema.sql:/etc/highload-arch/schema.sql"
      - "./db-data-leader/postgresql.conf:/etc/my_postgresql.conf"
      - "./db-data-leader/pg_hba.conf:/etc/my_pg_hba.conf"

    ports:
      - 5435:5432
    restart: always
    networks:
      ctl_net:
        ipv4_address: 172.16.238.91

  db-replica-1:
    image: postgres:14
    container_name: ha-db-replica-1
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=social_net
      - PGDATA=${PGDATA_LOCAL}
    volumes:
      - ./db-data-leader/pgslave:${PGDATA_LOCAL}
      - "./db-data-replica/postgresql.conf:${PGDATA_LOCAL}/postgresql.conf"
      - ./db-data-replica/standby.signal:${PGDATA_LOCAL}/standby.signal
    ports:
      - 5433:5432
    restart: always
    networks:
      ctl_net:
        ipv4_address: 172.16.238.92

  db-replica-2:
      image: postgres:14
      container_name: ha-db-replica-2
      environment:
        - POSTGRES_USER=admin_user
        - POSTGRES_PASSWORD=1111
        - POSTGRES_DB=social_net
        - PGDATA=${PGDATA_LOCAL}
      volumes:
      - ./db-data-leader/pgslave:${PGDATA_LOCAL}
      - "./db-data-replica/postgresql.conf:${PGDATA_LOCAL}/postgresql.conf"
      - ./db-data-replica/standby.signal:${PGDATA_LOCAL}/standby.signal
      ports:
        - 5434:5432
      restart: always
      networks:
        ctl_net:
          ipv4_address: 172.16.238.93

  db-cache:
    image: redis:7.2.3
    container_name: ha-db-cache
    #environment:
    #volumes:
    ports:
      - 6379:6379
    restart: always
    networks:
      ctl_net:
        ipv4_address: 172.16.238.94


  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: highload-arch-backend
    command: bash -c 'while true; do sleep 1; done'
    ports:
      - "8083:8083"
    networks:
      ctl_net:
        ipv4_address: 172.16.238.95

  db-tarantool:
    image: tarantool/tarantool:latest
    platform: "linux/amd64"
    container_name: ha-db-tarantool
    command: tarantool /opt/tarantool/app.lua
    environment:
      - TARANTOOL_USER_NAME=admin_user
      - TARANTOOL_USER_PASSWORD=1111
    volumes:
      - "./tarantool/app.lua:/opt/tarantool/app.lua"
    ports:
      - 3301:3301
    restart: always
    networks:
      ctl_net:
        ipv4_address: 172.16.238.101

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: ha-rabbitmq
    environment:
      - "RABBITMQ_DEFAULT_PASS=pass"
      - "RABBITMQ_DEFAULT_USER=user"
    #volumes:
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    networks:
      ctl_net:
        ipv4_address: 172.16.238.105


networks:
  ctl_net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

volumes:
  db-data-leader:
  db-data-replica:
  db-data-2: