global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: dialogs-service
    metrics_path: /api/v2/metrics
    static_configs:
      - targets: ['172.16.238.99:8086']
  